package it.unimib.disco.bimib.cyTRON.view;

import it.unimib.disco.bimib.cyTRON.controller.DatasetController;

public class MainFrame extends javax.swing.JFrame {

    private final DatasetController datasetController;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        // instantiate the controllers
        datasetController = new DatasetController();
        
        // draws the interface
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        datasetsPanel = new javax.swing.JPanel();
        datasetsPanelList = new javax.swing.JPanel();
        datasetsListScrollPane = new javax.swing.JScrollPane();
        datasetsList = new javax.swing.JList<>();
        importDatasetButton = new javax.swing.JButton();
        deleteDatasetButton = new javax.swing.JButton();
        currentDatasetPanel = new javax.swing.JPanel();
        genesPanelList = new javax.swing.JPanel();
        renameGeneButton = new javax.swing.JButton();
        deleteGeneButton = new javax.swing.JButton();
        genesScrollPane = new javax.swing.JScrollPane();
        genesList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("cyTRON");
        setMinimumSize(new java.awt.Dimension(1280, 720));

        datasetsPanelList.setBorder(javax.swing.BorderFactory.createTitledBorder("Datasets"));

        datasetsList.setModel(datasetController.getDatasetsListModel());
        datasetsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        datasetsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasetsListMouseClicked(evt);
            }
        });
        datasetsListScrollPane.setViewportView(datasetsList);

        importDatasetButton.setText("Import");
        importDatasetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importDatasetButtonActionPerformed(evt);
            }
        });

        deleteDatasetButton.setText("Delete");
        deleteDatasetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDatasetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datasetsPanelListLayout = new javax.swing.GroupLayout(datasetsPanelList);
        datasetsPanelList.setLayout(datasetsPanelListLayout);
        datasetsPanelListLayout.setHorizontalGroup(
            datasetsPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasetsPanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datasetsPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datasetsListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(datasetsPanelListLayout.createSequentialGroup()
                        .addComponent(importDatasetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteDatasetButton)))
                .addContainerGap())
        );
        datasetsPanelListLayout.setVerticalGroup(
            datasetsPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasetsPanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datasetsListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(datasetsPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importDatasetButton)
                    .addComponent(deleteDatasetButton))
                .addContainerGap())
        );

        currentDatasetPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        genesPanelList.setBorder(javax.swing.BorderFactory.createTitledBorder("Genes"));
        genesPanelList.setPreferredSize(new java.awt.Dimension(300, 320));

        renameGeneButton.setText("Rename");
        renameGeneButton.setToolTipText("");
        renameGeneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameGeneButtonActionPerformed(evt);
            }
        });

        deleteGeneButton.setText("Delete");
        deleteGeneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGeneButtonActionPerformed(evt);
            }
        });

        genesList.setModel(datasetController.getGenesListModel());
        genesScrollPane.setViewportView(genesList);

        javax.swing.GroupLayout genesPanelListLayout = new javax.swing.GroupLayout(genesPanelList);
        genesPanelList.setLayout(genesPanelListLayout);
        genesPanelListLayout.setHorizontalGroup(
            genesPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genesPanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genesPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(genesPanelListLayout.createSequentialGroup()
                        .addComponent(renameGeneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(deleteGeneButton)))
                .addContainerGap())
        );
        genesPanelListLayout.setVerticalGroup(
            genesPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genesPanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(genesPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renameGeneButton)
                    .addComponent(deleteGeneButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout currentDatasetPanelLayout = new javax.swing.GroupLayout(currentDatasetPanel);
        currentDatasetPanel.setLayout(currentDatasetPanelLayout);
        currentDatasetPanelLayout.setHorizontalGroup(
            currentDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genesPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        currentDatasetPanelLayout.setVerticalGroup(
            currentDatasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentDatasetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genesPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout datasetsPanelLayout = new javax.swing.GroupLayout(datasetsPanel);
        datasetsPanel.setLayout(datasetsPanelLayout);
        datasetsPanelLayout.setHorizontalGroup(
            datasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datasetsPanelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(currentDatasetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        datasetsPanelLayout.setVerticalGroup(
            datasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentDatasetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datasetsPanelList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Datasets", datasetsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importDatasetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importDatasetButtonActionPerformed
        ImportDatasetFrame importDatasetFrame = new ImportDatasetFrame(datasetController);
        importDatasetFrame.setLocationRelativeTo(null);
	importDatasetFrame.setVisible(true);
    }//GEN-LAST:event_importDatasetButtonActionPerformed

    private void deleteDatasetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDatasetButtonActionPerformed
        datasetController.deleteDataset(datasetsList.getSelectedIndex());
    }//GEN-LAST:event_deleteDatasetButtonActionPerformed

    private void datasetsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasetsListMouseClicked
        datasetController.updateLists(datasetsList.getSelectedIndex());
    }//GEN-LAST:event_datasetsListMouseClicked

    private void renameGeneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameGeneButtonActionPerformed
        RenameGeneFrame renameGeneFrame = new RenameGeneFrame(datasetController, genesList.getSelectedIndex(), datasetsList.getSelectedIndex());
        renameGeneFrame.setLocationRelativeTo(null);
	renameGeneFrame.setVisible(true);
    }//GEN-LAST:event_renameGeneButtonActionPerformed

    private void deleteGeneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGeneButtonActionPerformed
        datasetController.deleteGene(genesList.getSelectedIndex(), datasetsList.getSelectedIndex());
    }//GEN-LAST:event_deleteGeneButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel currentDatasetPanel;
    private javax.swing.JList<String> datasetsList;
    private javax.swing.JScrollPane datasetsListScrollPane;
    private javax.swing.JPanel datasetsPanel;
    private javax.swing.JPanel datasetsPanelList;
    private javax.swing.JButton deleteDatasetButton;
    private javax.swing.JButton deleteGeneButton;
    private javax.swing.JList<String> genesList;
    private javax.swing.JPanel genesPanelList;
    private javax.swing.JScrollPane genesScrollPane;
    private javax.swing.JButton importDatasetButton;
    private javax.swing.JButton renameGeneButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
