/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unimib.disco.bimib.cyTRON.view;

import java.awt.event.ItemEvent;
import java.io.File;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

import it.unimib.disco.bimib.cyTRON.controller.CommandExecutor;

/**
 *
 * @author Dalia
 */
public class OptionPanel extends javax.swing.JPanel {

    public enum FieldTitle {
        MODEL("model"), GRAPHML("graphml"), PDF("pdf"), HG("hg"), TP("tp"), PR("pr"), 
        SCALE_NODES("scale.nodes"), HEIGHT("height"), WIDTH("width"), 
        DISCONNECTED_NODES("disconnected"), PMIN("pmin"), EDGE_CEX("edge.cex"), 
        LABEL_EDGE_SIZE("label.edge.size"), EDGE_COLOR("edge.color"), EDGE_LWD("edge.lwd"),
        STATISTICAL_BOOTSTRAP("sb"), NON_PARAMETRIC_BOOTSTRAP("npb"),
        CORES_RATIO("cores.ratio"),
        N_BOOT("nboot");
        
        private String title;

        private FieldTitle(String title) {
            this.title = title;
        }

        public String getTitle() {
            return title;
        }
    };

    private File modelFile;
    private final CommandExecutor commandExecutor;
    private final JFrame frame;
    private Map<FieldTitle, String> parameters;

    public OptionPanel(CommandExecutor commandExecutor, JFrame frame) {
        this.commandExecutor = commandExecutor;
        this.frame = frame;
        this.parameters = new HashMap<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        modelButton = new javax.swing.JButton();
        outputCB = new javax.swing.JCheckBox();
        outputFileText = new javax.swing.JTextField();
        exportPdfCB = new javax.swing.JCheckBox();
        outputPdf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        confidenceLabel = new javax.swing.JLabel();
        tpCB = new javax.swing.JCheckBox();
        hgCB = new javax.swing.JCheckBox();
        prCB = new javax.swing.JCheckBox();
        scaleNodesCB = new javax.swing.JCheckBox();
        scaleNodesTB = new javax.swing.JFormattedTextField();
        heightLabel = new javax.swing.JLabel();
        heightTB = new javax.swing.JFormattedTextField();
        widthLabel = new javax.swing.JLabel();
        widthTB = new javax.swing.JFormattedTextField();
        pminLabel = new javax.swing.JLabel();
        pminTB = new javax.swing.JFormattedTextField();
        edgeCexTB = new javax.swing.JFormattedTextField();
        edgeCexLabel = new javax.swing.JLabel();
        disconnectedNodesCB = new javax.swing.JCheckBox();
        labelEdgeSizeCB = new javax.swing.JCheckBox();
        lesTB = new javax.swing.JFormattedTextField();
        edgeColorLabel = new javax.swing.JLabel();
        edgeColorTB = new javax.swing.JTextField();
        edgeLwdLabel = new javax.swing.JLabel();
        lwdTB = new javax.swing.JFormattedTextField();
        helpButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        parametricButton = new javax.swing.JRadioButton();
        statisticalButton = new javax.swing.JRadioButton();
        noBootstrapButton = new javax.swing.JRadioButton();
        bootstrapAlreadyCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        nBootTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        coreRatioTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        buttonGroup1.add(parametricButton);
        buttonGroup1.add(statisticalButton);
        buttonGroup1.add(noBootstrapButton);
        buttonGroup1.setSelected(noBootstrapButton.getModel(), true);

        modelButton.setText("Choose Model");
        modelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelButtonActionPerformed(evt);
            }
        });

        outputCB.setText("Choose graphml output file");
        outputCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                outputCBItemStateChanged(evt);
            }
        });

        outputFileText.setText(System.getProperty("user.home") + "/test.graphml");
        outputFileText.setEnabled(false);

        exportPdfCB.setText("Export PDF");
        outputPdf.setEnabled(false);
        exportPdfCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                exportPdfCBItemStateChanged(evt);
            }
        });

        outputPdf.setText(System.getProperty("user.home") + "/output.pdf");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exportPdfCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputFileText, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(outputPdf))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modelButton)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modelButton)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputCB)
                    .addComponent(outputFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportPdfCB)
                    .addComponent(outputPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("input/output file options", jPanel1);

        confidenceLabel.setText("Confidence");

        tpCB.setText("tp");

        hgCB.setText("hg");

        prCB.setText("pr");

        scaleNodesCB.setText("scale.nodes");
        scaleNodesCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scaleNodesCBItemStateChanged(evt);
            }
        });
        scaleNodesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleNodesCBActionPerformed(evt);
            }
        });

        scaleNodesTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        scaleNodesTB.setEnabled(false);

        heightLabel.setText("height");

        heightTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        heightTB.setText("2.0");

        widthLabel.setText("width");

        widthTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        widthTB.setText("3.0");

        pminLabel.setText("pmin");

        pminTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        pminTB.setText("0.05");

        edgeCexTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        edgeCexTB.setText("1.0");

        edgeCexLabel.setText("edge.cex");

        disconnectedNodesCB.setText("Show disconnected nodes");
        disconnectedNodesCB.setToolTipText("");

        labelEdgeSizeCB.setText("labels.edge.size");
        labelEdgeSizeCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                labelEdgeSizeCBItemStateChanged(evt);
            }
        });
        labelEdgeSizeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelEdgeSizeCBActionPerformed(evt);
            }
        });

        lesTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        lesTB.setEnabled(false);

        edgeColorLabel.setText("edge.color");

        edgeColorTB.setText("black");
        edgeColorTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgeColorTBActionPerformed(evt);
            }
        });

        edgeLwdLabel.setText("edge.lwd");

        lwdTB.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getNumberInstance(Locale.US))));
        lwdTB.setText("3");

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(heightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(scaleNodesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scaleNodesTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(245, 245, 245))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disconnectedNodesCB)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pminLabel)
                                    .addComponent(edgeCexLabel)
                                    .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pminTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(widthTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edgeCexTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(confidenceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prCB)
                            .addComponent(hgCB)
                            .addComponent(tpCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdgeSizeCB)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edgeLwdLabel)
                                    .addComponent(edgeColorLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edgeColorTB)
                            .addComponent(lesTB)
                            .addComponent(lwdTB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpButton))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEdgeSizeCB)
                            .addComponent(lesTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edgeColorLabel)
                            .addComponent(edgeColorTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edgeLwdLabel)
                            .addComponent(lwdTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hgCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confidenceLabel)
                            .addComponent(tpCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prCB)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scaleNodesCB)
                            .addComponent(scaleNodesTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightLabel)
                            .addComponent(heightTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widthLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disconnectedNodesCB)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pminLabel)
                            .addComponent(pminTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edgeCexTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edgeCexLabel))
                        .addContainerGap(60, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton))
        );

        jTabbedPane1.addTab("export.graphml parameters", jPanel2);

        parametricButton.setLabel("parametric bootstrap");

        statisticalButton.setLabel("statistical bootstrap");

        noBootstrapButton.setLabel("no bootstrap");
        noBootstrapButton.setEnabled(true);
        noBootstrapButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noBootstrapStateChanged(evt);
            }
        });

        bootstrapAlreadyCB.setLabel("bootstrap already prepared");
        bootstrapAlreadyCB.setEnabled(false);
        bootstrapAlreadyCB.setSelected(true);
        bootstrapAlreadyCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boostrapAlreadyStateChanged(evt);
            }
        });
        bootstrapAlreadyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootstrapAlreadyCBActionPerformed(evt);
            }
        });

        jLabel1.setText("number of bootstraps sampling to be performed");

        nBootTF.setText("100");
        nBootTF.setEnabled(false);

        jLabel2.setText("core.ratio");

        coreRatioTF.setText("100");
        coreRatioTF.setEnabled(false);

        jLabel3.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bootstrapAlreadyCB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nBootTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(coreRatioTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statisticalButton)
                            .addComponent(parametricButton)
                            .addComponent(noBootstrapButton))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noBootstrapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statisticalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parametricButton)
                .addGap(44, 44, 44)
                .addComponent(bootstrapAlreadyCB)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nBootTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(coreRatioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("bootstrap options", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bootstrapAlreadyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootstrapAlreadyCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bootstrapAlreadyCBActionPerformed

    private void boostrapAlreadyStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boostrapAlreadyStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            coreRatioTF.setEnabled(false);
            nBootTF.setEnabled(false);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            coreRatioTF.setEnabled(true);
            nBootTF.setEnabled(true);
        }
    }//GEN-LAST:event_boostrapAlreadyStateChanged

    private void noBootstrapStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noBootstrapStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            bootstrapAlreadyCB.setSelected(true);
            bootstrapAlreadyCB.setEnabled(false);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            bootstrapAlreadyCB.setEnabled(true);
            bootstrapAlreadyCB.setSelected(false);
            
        }
        
    }//GEN-LAST:event_noBootstrapStateChanged
    
    // TODO: capire quale codice è autogenerato e quale no a partire da qui
    private void edgeColorTBActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void labelEdgeSizeCBActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void scaleNodesCBActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void modelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            modelFile = fc.getSelectedFile();
        }
    }

    private void exportPdfCBItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            outputPdf.setEnabled(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            outputPdf.setEnabled(false);
        }

        validate();
        repaint();
    }

    private void outputCBItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            outputFileText.setEnabled(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            outputFileText.setEnabled(false);
        }

        validate();
        repaint();
    }

    private void scaleNodesCBItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            scaleNodesTB.setEnabled(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            scaleNodesTB.setEnabled(false);
        }

        validate();
        repaint();
    }

    private void labelEdgeSizeCBItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            lesTB.setEnabled(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            lesTB.setEnabled(false);
        }

        validate();
        repaint();
    }

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder parameters = new StringBuilder();
        parameters.append("model: a reconstructed model\n");
        parameters.append("models: a vector containing the name of the algorithms used\n");
        parameters.append("fontsize: for node names\n");
        parameters.append("height: for node height\n");
        parameters.append("width: for node width\n");
        parameters.append("height.logic: for logical nodes\n");
        parameters.append("pf: should I print Prima Facie?\n");
        parameters.append("disconnected: should I print disconnected nodes?\n");
        parameters.append("scale.nodes: node scaling coefficient\n");
        parameters.append("title: title of the plot\n");
        parameters.append("confidence: should I add confidence information?\n");
        parameters.append("pmin: p-value cutoff\n");
        parameters.append("label.edge.size: size of edge labels\n");
        parameters.append("expand: should I expand hypotheses?\n");
        parameters.append("genes: visualise only genes in this list\n");
        parameters.append("edge.color: edge color\n");
        parameters.append("file: string containing file name for PDF output\n");
        parameters.append("pathways: a vetor containing pathways information\n");
        parameters.append("lwd: edge base lwd\n");
        parameters.append("samples.annotation\n");
        JOptionPane.showMessageDialog(null, parameters.toString(), "Parametri disponibili",
                JOptionPane.QUESTION_MESSAGE);
    }

    public Map<FieldTitle, String> getParameters() {
        if (parameters == null) {
            parameters = new HashMap<>();
        }

        parameters.put(FieldTitle.MODEL, modelFile.getAbsolutePath());

        if (outputCB.isSelected()) {
            parameters.put(FieldTitle.GRAPHML, outputFileText.getText());
        }
        
        if (exportPdfCB.isSelected()) {
            parameters.put(FieldTitle.PDF, outputPdf.getText());
        }
        
        if (hgCB.isSelected()) {
            parameters.put(FieldTitle.HG, "'hg'");
        }
        
        if (tpCB.isSelected()) {
            parameters.put(FieldTitle.TP, "'tp'");
        }
        
        if (prCB.isSelected()) {
            parameters.put(FieldTitle.PR, "'pr'");
        }
        
        if (scaleNodesCB.isSelected()) {
            parameters.put(FieldTitle.SCALE_NODES, scaleNodesTB.getText());
        }
        
        parameters.put(FieldTitle.HEIGHT, heightTB.getText());
        
        parameters.put(FieldTitle.WIDTH, widthTB.getText());

        parameters.put(FieldTitle.DISCONNECTED_NODES, 
                disconnectedNodesCB.isSelected() ? "TRUE" : "FALSE");
        
        parameters.put(FieldTitle.PMIN, pminTB.getText());
        
        parameters.put(FieldTitle.EDGE_CEX, edgeCexTB.getText());

        if (labelEdgeSizeCB.isSelected()) {
            parameters.put(FieldTitle.LABEL_EDGE_SIZE, lesTB.getText());
        }

        parameters.put(FieldTitle.EDGE_COLOR, "'" + edgeColorTB.getText() + "'");

        parameters.put(FieldTitle.EDGE_LWD, lwdTB.getText());
        
        if (buttonGroup1.isSelected(parametricButton.getModel())) {
            parameters.put(FieldTitle.NON_PARAMETRIC_BOOTSTRAP, "true");
        } else  if (buttonGroup1.isSelected(statisticalButton.getModel())) {
            parameters.put(FieldTitle.STATISTICAL_BOOTSTRAP, "true");
        }
        
        if (!bootstrapAlreadyCB.isSelected()) {
            double ratio = Double.parseDouble(coreRatioTF.getText()) / 100;
            parameters.put(FieldTitle.CORES_RATIO, String.valueOf(ratio));
            parameters.put(FieldTitle.N_BOOT, nBootTF.getText());
        }
        
        return parameters;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bootstrapAlreadyCB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel confidenceLabel;
    private javax.swing.JTextField coreRatioTF;
    private javax.swing.JCheckBox disconnectedNodesCB;
    private javax.swing.JLabel edgeCexLabel;
    private javax.swing.JFormattedTextField edgeCexTB;
    private javax.swing.JLabel edgeColorLabel;
    private javax.swing.JTextField edgeColorTB;
    private javax.swing.JLabel edgeLwdLabel;
    private javax.swing.JCheckBox exportPdfCB;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JFormattedTextField heightTB;
    private javax.swing.JButton helpButton;
    private javax.swing.JCheckBox hgCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox labelEdgeSizeCB;
    private javax.swing.JFormattedTextField lesTB;
    private javax.swing.JFormattedTextField lwdTB;
    private javax.swing.JButton modelButton;
    private javax.swing.JTextField nBootTF;
    private javax.swing.JRadioButton noBootstrapButton;
    private javax.swing.JCheckBox outputCB;
    private javax.swing.JTextField outputFileText;
    private javax.swing.JTextField outputPdf;
    private javax.swing.JRadioButton parametricButton;
    private javax.swing.JLabel pminLabel;
    private javax.swing.JFormattedTextField pminTB;
    private javax.swing.JCheckBox prCB;
    private javax.swing.JCheckBox scaleNodesCB;
    private javax.swing.JFormattedTextField scaleNodesTB;
    private javax.swing.JRadioButton statisticalButton;
    private javax.swing.JCheckBox tpCB;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JFormattedTextField widthTB;
    // End of variables declaration//GEN-END:variables
}
