package it.unimib.disco.bimib.cyTRON;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.HashMap;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

import org.cytoscape.work.FinishStatus;
import org.cytoscape.work.ObservableTask;
import org.cytoscape.work.TaskObserver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dalia
 */
public class OptionPanel extends javax.swing.JPanel {
	private File modelFile;
	private CommandExecutor commandExecutor;
	private JFrame frame;

	/**
	 * Creates new form NewJPanel
	 */
	public OptionPanel(CommandExecutor commandExecutor, JFrame frame) {
		this.commandExecutor = commandExecutor;
		this.frame = frame;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton3 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		modelButton = new javax.swing.JButton();
		outputFileText = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		loadButton = new javax.swing.JButton();
		exportPdfCB = new javax.swing.JCheckBox();
		outputPdf = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		hgCB = new javax.swing.JCheckBox();
		tpCB = new javax.swing.JCheckBox();
		prCB = new javax.swing.JCheckBox();
		jLabel3 = new javax.swing.JLabel();
		scaleNodesTB = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		heightTB = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		widthTB = new javax.swing.JTextField();
		disconnectedNodesCB = new javax.swing.JCheckBox();
		jLabel7 = new javax.swing.JLabel();
		pminTB = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		edgeCexTB = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		lesTB = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		edgeColorTB = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		lwdTB = new javax.swing.JTextField();

		jButton3.setText("jButton3");

		jLabel6.setText("jLabel6");

		jLabel12.setText("jLabel12");

		modelButton.setText("Choose model");

		outputFileText.setText(System.getProperty("user.home") + "/test.graphml");

		jLabel1.setText("Choose graphml output file");

		loadButton.setText("Load");

		exportPdfCB.setText("Export PDF");
		exportPdfCB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox5ActionPerformed(evt);
			}
		});

		outputPdf.setText("jTextField10");
		outputPdf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField10ActionPerformed(evt);
			}
		});
		outputPdf.setEnabled(false);
		
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(54, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(modelButton).addGap(132, 132,
												132))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(loadButton)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(27, 27, 27).addComponent(outputFileText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(149, 149, 149))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(exportPdfCB)
										.addGap(77, 77, 77)
										.addComponent(outputPdf, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22).addComponent(modelButton)
						.addGap(28, 28, 28)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(outputFileText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(exportPdfCB).addComponent(outputPdf,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(14, 14, 14).addComponent(loadButton).addContainerGap(101, Short.MAX_VALUE)));

		jTabbedPane1.addTab("input/output file options", jPanel1);

		jButton4.setLabel("Help");

		jLabel2.setText("Confidence");

		hgCB.setText("hg");
		hgCB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		tpCB.setText("tp");

		prCB.setText("pr");

		jLabel3.setText("scale.nodes");

		scaleNodesTB.setText("NA");

		jLabel4.setText("height");

		heightTB.setText("2.0");
		heightTB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		jLabel5.setText("width");

		widthTB.setText("3.0");

		disconnectedNodesCB.setText("Show disconnected nodes");

		jLabel7.setText("pmin");

		pminTB.setText("0.05");

		jLabel8.setText("edge.cex");

		edgeCexTB.setText("1.0");

		jLabel9.setText("label.edge.size");

		lesTB.setText("NA");

		jLabel10.setText("edge.color");

		edgeColorTB.setText("black");

		jLabel11.setText("edge lwd");

		lwdTB.setText("3");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(hgCB).addComponent(tpCB).addComponent(prCB,
												javax.swing.GroupLayout.PREFERRED_SIZE, 49,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(68, 68, 68)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel9).addComponent(jLabel10).addComponent(jLabel11))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lwdTB, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lesTB, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(edgeColorTB, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel3).addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(scaleNodesTB, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(heightTB, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(widthTB, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addComponent(jLabel5)).addContainerGap(101, Short.MAX_VALUE))
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton4)
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
										disconnectedNodesCB)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7).addComponent(jLabel8))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(edgeCexTB, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(pminTB, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
														javax.swing.GroupLayout.PREFERRED_SIZE))))))
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGap(5, 5, 5)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(hgCB).addComponent(jLabel9)
								.addComponent(lesTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2).addComponent(tpCB))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel10).addComponent(edgeColorTB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(prCB).addComponent(jLabel11).addComponent(lwdTB,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(5, 5, 5)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(scaleNodesTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addGap(0, 0, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(heightTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(widthTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(disconnectedNodesCB)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(pminTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(edgeCexTB, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
						.addComponent(jButton4)));

		jTabbedPane1.addTab("export.graphml parameters", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));

		jTabbedPane1.getAccessibleContext().setAccessibleName("");
		
		modelButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				final JFileChooser fc = new JFileChooser();
				int returnVal = fc.showOpenDialog(loadButton);

				if (returnVal == JFileChooser.APPROVE_OPTION) {
					modelFile = fc.getSelectedFile();
				}
			}
		});

		loadButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				File scriptFile = generateScript();

				TaskObserver observer = new TaskObserver() {
					@Override
					public void taskFinished(ObservableTask arg0) {
						System.out.println("TaskFinished");
					}

					@Override
					public void allFinished(FinishStatus arg0) {
						System.out.println("TaskAllFinished");

					}
				};

				HashMap<String, Object> mappa = new HashMap<String, Object>();
				mappa.put("inputFile", scriptFile.getAbsolutePath());
				commandExecutor.executeCommand("cytron", "import", mappa, observer);
				frame.dispose();
			}
		});
		
		exportPdfCB.addItemListener(new ItemListener() {
			
			@Override
			public void itemStateChanged(ItemEvent e) {
				if(e.getStateChange() == ItemEvent.SELECTED){
                    outputPdf.setEnabled(true);
                }
                else if(e.getStateChange() == ItemEvent.DESELECTED){
                    outputPdf.setEnabled(false);
                }

                validate();
                repaint();
				
			}
		});

	}// </editor-fold>

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	
	private File generateScript() {
		StringBuilder scriptBuilder = new StringBuilder();
		String modelPath = modelFile.getAbsolutePath();
		String outputPath = outputFileText.getText();
		
		String modelName = "";
		int lastDot = modelPath.lastIndexOf('.');
		if (modelPath.contains("\\")) {
			int lastBackslash = modelPath.lastIndexOf('\\');
			
			if (lastBackslash < lastDot)
				modelName = modelPath.substring(lastBackslash + 1, lastDot);
			else
				modelName = modelPath.substring(lastBackslash + 1);
		} else {
			int lastSlash = modelPath.lastIndexOf('/');
			
			if (lastSlash == -1)
				modelName = modelPath;
			else if (lastSlash < lastDot)
				modelName = modelPath.substring(lastSlash + 1, lastDot);
			else
				modelName = modelName.substring(lastSlash + 1);
		}
		
		scriptBuilder.append("library('TRONCO')\n");
		scriptBuilder.append("load('" + modelPath + "')\n");
		scriptBuilder.append("export.graphml(" + modelName + ", '" + outputPath + "'");
		scriptBuilder.append(scaleNodesTB.getText().equals("NA") ? "" : ", scale.nodes = " + scaleNodesTB.getText());
		scriptBuilder.append(", confidence = c(");
		scriptBuilder.append(hgCB.isSelected() ? "'hg'" : "");
		if (tpCB.isSelected() && hgCB.isSelected()) {
			scriptBuilder.append(", 'tp'");
		} else if (tpCB.isSelected()) {
			scriptBuilder.append("'tp'");
		}
		if ((tpCB.isSelected() || hgCB.isSelected()) && prCB.isSelected()) {
			scriptBuilder.append(", 'pr'");
		} else if (prCB.isSelected()) {
			scriptBuilder.append("'pr'");
		}
		scriptBuilder.append(")");
		scriptBuilder.append(")");
		
		System.out.println("-----------------------------\n\n");
		System.out.println(scriptBuilder.toString());
		System.out.println("-----------------------------\n\n");
		
		File outputFile = null;
		try {
			outputFile = File.createTempFile("cytron_script", "R");
			Writer writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outputFile)));
			writer.write(scriptBuilder.toString());
			writer.close();	
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		return outputFile;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton modelButton;
	private javax.swing.JButton loadButton;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JCheckBox hgCB;
	private javax.swing.JCheckBox tpCB;
	private javax.swing.JCheckBox prCB;
	private javax.swing.JCheckBox disconnectedNodesCB;
	private javax.swing.JCheckBox exportPdfCB;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField outputFileText;
	private javax.swing.JTextField outputPdf;
	private javax.swing.JTextField scaleNodesTB;
	private javax.swing.JTextField heightTB;
	private javax.swing.JTextField widthTB;
	private javax.swing.JTextField pminTB;
	private javax.swing.JTextField edgeCexTB;
	private javax.swing.JTextField lesTB;
	private javax.swing.JTextField edgeColorTB;
	private javax.swing.JTextField lwdTB;
	// End of variables declaration
}
